export const ROUTES = {
  ROOT: '/',
  LANDING: '/auth/landing',
  LOGIN: '/auth/login',
  SIGNUP: '/auth/signup',
  MAIN: '/main',
  HOMEPAGE: '/homepage',
  RECORD: '/main/record',
  RESULT: '/main/result',
  RESULT_LOADING: '/main/loading',
  RESULT_SHARE: '/main/share',
  MYPAGE: '/mypage',
  MYPAGE_STATS: '/mypage/stats',
  MYPAGE_HISTORY: '/mypage/history',
  MYPAGE_DIFFICULTY: '/mypage/difficulty',
  DIFFICULTY: '/auth/difficulty',
};
