export const ROUTES = {
  ROOT: '/',
  LANDING: '/auth/landing',
  LOGIN: '/auth/login',
  SIGNUP: '/auth/signup',
  MAIN: '/main',
  HOMEPAGE: '/homepage',
  RECORD: '/main/record',
  RESULT: (speechId: number) => `/main/result/${speechId}`,
  RESULT_LOADING: (speechId: number) => `/main/loading/${speechId}`,
  RESULT_SHARE: '/main/share',
  MYPAGE: '/mypage',
  MYPAGE_STATS: '/mypage/stats',
  MYPAGE_HISTORY: '/mypage/history',
  MYPAGE_DIFFICULTY: '/mypage/difficulty',
  DIFFICULTY: '/auth/difficulty',
  FIND_ID: '/auth/find-id',
  FIND_PASSWORD: '/auth/find-password',
};
